udo: false
language: python
python:
  - "2.7"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - python: 3.8
      env: TOXENV=flake8
cache:
  directories:
    - $HOME/.pip_cache
install:
  - "travis_retry pip install setuptools --upgrade"
  - "pip install tox coveralls"
script:
  - tox -e $TOXENV
after_success:
  - coveralls -v